# Autogenerated config.py
# --- Recommended for both Pyright and Pylint ---{{{
# type: ignore[reportUndefinedVariable] # For Pyright
# pylint: disable=E0602 # For Pylint
"""
config file for qutebrowser
"""
import sys

#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only.
#     This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only,
#     unless a cookie is already set for the domain.
#     On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set("content.cookies.accept", "all", "chrome-devtools://*")

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only.
#     This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only,
#     unless a cookie is already set for the domain.
#     On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set("content.cookies.accept", "all", "devtools://*")

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set("content.headers.accept_language", "", "https://matchmaker.krunker.io/*")

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{upstream_browser_version_short}`: The
# corresponding Safari/Chrome   version, but only with its major
# version. * `{qutebrowser_version}`: The currently running qutebrowser
# version.  The default value is equal to the default user agent of
# QtWebKit/QtWebEngine, but with the `QtWebEngine/...` part removed for
# increased compatibility.  Note that the value read from JavaScript is
# always the global value.
# Type: FormatString
config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 ({os_info}; rv:136.0) Gecko/20100101 Firefox/139.0",
    "https://accounts.google.com/*",
)

# Load images automatically in web pages.
# Type: Bool
config.set("content.images", True, "chrome-devtools://*")

# Load images automatically in web pages.
# Type: Bool
config.set("content.images", True, "devtools://*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "chrome-devtools://*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "devtools://*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "chrome://*/*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "qute://*/*")

# Allow locally loaded documents to access remote URLs.
# Type: Bool
config.set(
    "content.local_content_can_access_remote_urls",
    True,
    "file:///home/haku/.local/share/qutebrowser/userscripts/*",
)

# Allow locally loaded documents to access other local URLs.
# Type: Bool
config.set(
    "content.local_content_can_access_file_urls",
    False,
    "file:///home/haku/.local/share/qutebrowser/userscripts/*",
)  # }}}

# Haku Main <<<
# {{{
# setting for diff OS
if sys.platform == "darwin":  # macOS
    c.tabs.position = "top"
    c.fonts.default_size = "20pt"
    c.fonts.web.size.default = 20
elif sys.platform.startswith("linux"):
    c.tabs.position = "bottom"
    # c.tabs.width = "2%"
    c.fonts.default_size = "15pt"
    c.fonts.web.size.default = 18
else:
    c.tabs.position = "left"
    c.tabs.position = "bottom"
c.scrolling.smooth = True
c.search.incremental = False
c.messages.timeout = 0
# remove copy request
c.content.javascript.clipboard = "access-paste"
# allow PDF viewer
c.content.pdfjs = True

# avoid error notice in caret/visual mode
c.content.javascript.log_message.excludes = {
    "userscript:_qute_stylesheet": [
        "*Refused to apply inline style because it violates the following \
        Content Security Policy directive: *"
    ],
    "userscript:_qute_js": ["*TrustedHTML*"],
}


# normal keys
config.bind("K", "tab-next")
config.bind("J", "tab-prev")
config.bind(
    "z",
    "config-cycle tabs.show always never;; config-cycle statusbar.show always never",
)
config.bind("d", "cmd-run-with-count 20 scroll down")
config.bind("u", "cmd-run-with-count 20 scroll up")
config.bind("x", "tab-close")
config.bind("X", "tab-only -p")
# config.bind("w", "mode-enter passthrough", mode="normal")
config.bind("<shift-u>", "undo")
config.bind("=", "zoom-in")
config.bind("0", "zoom")

# meta keys : command / windows
## for mac; linux suppose use one window
config.bind("<Meta-1>", "tab-select 0/1")
config.bind("<Meta-2>", "tab-select 1/1")
config.bind("<Meta-shift-1>", "tab-give 0")
config.bind("<Meta-shift-2>", "tab-give 1")

# alt keys
## Nav
config.bind("<alt-0>", "tab-move")
config.bind("<alt-shift-j>", "tab-move -")
config.bind("<alt-shift-k>", "tab-move +")
config.bind("<alt-a>", "fake-key <ctrl-a>", mode="insert")
config.bind("<alt-h>", "fake-key <alt-shift-left><delete>", mode="insert")
config.bind("<alt-b>", "fake-key <ctrl-left>", mode="insert")
config.bind("<alt-f>", "fake-key <ctrl-right>", mode="insert")
config.bind("<alt-d>", "fake-key <alt-shift-right><delete>", mode="insert")
config.bind("<alt-p>", "tab-pin")
config.bind("<alt-s>", "config-source")
config.bind("<alt-e>", "tab-focus last")
config.bind("<alt-j>", "click-element position 1300,300")
## function for look
config.bind(
    "<alt-d>", 'yank selection;; spawn --detach bash -c "open dict://$(pbpaste)"'
)
config.bind("tt", "spawn --userscript ./translate_ch_jp_message-info.sh", mode="caret")
config.bind("<ctrl-f>", "spawn --userscript qute-pass.py", mode="normal")
config.bind("<Escape>", "mode-leave;;clear-messages", mode="caret")
config.bind(
    "<Escape>",
    "clear-messages;;clear-keychain ;; search ;; fullscreen --leave",
    mode="normal",
)

config.bind("Q", "macro-record")
# config.bind(
#     "tt", "spawn --userscript ~/.local/share/qutebrowser/userscripts/qute-trans"
# )
config.bind("<alt-b>", "cmd-set-text -s :bookmark-load")
config.bind("<alt-shift-b>", "cmd-set-text -s :bookmark-load -t")
# ctrl keys
## Emacs-Like
config.bind("<ctrl-h>", "fake-key <backspace>", mode="insert")
config.bind("<ctrl-f>", "fake-key <right>", mode="insert")
config.bind("<ctrl-b>", "fake-key <left>", mode="insert")
config.bind("<ctrl-n>", "fake-key <down>", mode="insert")
config.bind("<ctrl-p>", "fake-key <up>", mode="insert")
config.bind("<ctrl-j>", "completion-item-focus next", mode="command")
config.bind("<ctrl-k>", "completion-item-focus prev", mode="command")
config.bind("<ctrl-a>", "fake-key <home>", mode="insert")
config.bind("<ctrl-e>", "fake-key <end>", mode="insert")
config.bind("<ctrl-k>", "fake-key <Ctrl-Shift-Right><delete>", mode="insert")
config.bind("<ctrl-d>", "fake-key <delete>", mode="insert")
## functions
config.bind("<ctrl-t>", "cmd-set-text -s :tab-take")
config.bind("<ctrl-k>", "mode-enter set_mark")


#
# Haku Main >>>}}}

# Haku Check
# check platform
config.bind("<alt-t>", f"cmd-set-text -s :{sys.platform}")
# config.bind("<alt-t>", "spawn --userscript qute-pass.py")
config.bind(
    "ee",
    "spawn --detach wezterm cli spawn  --new-window -- pass insert websites/{url:host}/",
)
# Replace 'kitty -e' with the wezterm equivalent
# Haku Check
