#
# Top Level Folders
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_STATE_HOME="${HOME}/.local/state"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

stty -ixon
# Create XDG directories if they don't exist
mkdir -p "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME" "$XDG_STATE_HOME" "$ZDOTDIR"
mkdir -p "$XDG_CONFIG_HOME/zsh" "$XDG_DATA_HOME/zsh" "$XDG_CACHE_HOME/zsh" "$XDG_STATE_HOME/zsh"

source "$ZDOTDIR/zshrc.d/env.zsh"
