# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Plugins
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [[ -f $ZDOTDIR/.p10k.zsh ]];then
  source $ZDOTDIR/.p10k.zsh
fi
source $HOME/.zsh-plugins/powerlevel10k/powerlevel10k.zsh-theme
source $HOME/.zsh-plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.zsh-plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# Start from insertmode for zsh-vi-mode, needed before source zsh-vi-mode
function zvm_config() {
  ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
}
source $HOME/.zsh-plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# Zshrc 
# autocomplete hidden files
# auto completion init, need highter priority
autoload -U compinit; compinit -d "$XDG_CACHE_HOME/zsh/zcompdump"
_comp_options+=(globdots)
source ~/dotfiles/zsh/external/completion.zsh
source "$ZDOTDIR/zshrc.d/aliases.zsh"
source "$ZDOTDIR/zshrc.d/options.zsh"
source "$ZDOTDIR/zshrc.d/tools.zsh"
source "$ZDOTDIR/zshrc.d/functions.zsh"


# chocolate
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#d2691e'
# autoload -Uz cursor_mode && cursor_mode
# autoload -Uz prompt_purification_setup && prompt_purification_setup
