# Plugins
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [[ -f $HOME/.p10k.zsh ]];then
  source $HOME/.p10k.zsh
fi
source $HOME/.zsh-plugins/powerlevel10k/powerlevel10k.zsh-theme
source $HOME/.zsh-plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source $HOME/.zsh-plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.zsh-plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# Zshrc 
# autocomplete hidden files
# auto completion init, need highter priority
[[ -d "$XDG_CACHE_HOME/zsh" ]] || mkdir -p "$XDG_CACHE_HOME/zsh"
autoload -U compinit; compinit -d "$XDG_CACHE_HOME/zsh/zcompdump"
_comp_options+=(globdots)
source ~/dotfiles/zsh/external/completion.zsh
source "$ZDOTDIR/zshrc.d/aliases.zsh"
source "$ZDOTDIR/zshrc.d/options.zsh"
source "$ZDOTDIR/zshrc.d/tools.zsh"
source "$ZDOTDIR/zshrc.d/functions.zsh"

# chocolate
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#d2691e'
# autoload -Uz cursor_mode && cursor_mode
# autoload -Uz prompt_purification_setup && prompt_purification_setup


zvm_after_init_commands+=(
#   #for dirhistory
  "bindkey -s '^K' '^[[1;3A'" "bindkey -M vicmd -s '^K' '^[[1;3A'"
  "bindkey -s '^U' '^[[1;3C'" "bindkey -M vicmd -s '^U' '^[[1;3C'" 
  "bindkey -s '^O' '^[[1;3D'" "bindkey -M vicmd -s '^O' '^[[1;3D'"
  "bindkey '^J' open-nvim" "bindkey -M vicmd '^J' open-nvim"
  "bindkey '^H' backward-delete-char"
  "bindkey '^V' paste-from-clipboard"
  "bindkey '^S' prepend-sudo"
 )
